In [158]:
from sklearn.datasets import load_diabetes

In [180]:
x,y = load_diabetes(return_X_y=True)
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [181]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [182]:
len(y)

442

In [183]:
from sklearn.linear_model import LinearRegression

In [184]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=3)

In [185]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [186]:
y_pred = model.predict(x_test)
y_pred

array([ 99.48235947, 181.25429903, 106.61572846, 123.10541923,
       183.04909567,  83.29913847, 130.54854188, 233.85654301,
       155.00942627, 171.46626454, 171.06003791, 192.94190885,
       147.25129841, 214.5307459 ,  47.50252863, 142.43786422,
       119.95723033, 209.7179434 , 185.71531692, 147.23625586,
       150.40785093, 102.60018559, 170.78899034, 177.8219416 ,
       152.40388316, 187.08466299, 197.72314739, 204.83066546,
       132.09655487, 158.42112429, 260.54948673, 125.48180691,
       195.29165994, 125.76882485, 163.21646899,  58.37895843,
       158.14323269, 103.4034084 , 128.04980829, 161.3128156 ,
       146.00080757, 219.57659671, 126.64096152, 131.12134464,
       150.1627216 ,  92.3404223 , 120.10323463, 261.33608538,
       150.22171365, 197.82772808, 145.97361477, 104.56119742,
       139.47230609, 192.90101701, 159.2347891 , 135.21956019,
       120.30423162, 262.94731714, 255.46123067, 151.24338655,
       153.11282489, 128.59191597,  69.02540213, 136.99

In [187]:
from sklearn.metrics import r2_score

In [188]:
results = r2_score(y_test,y_pred)
results

0.4161792211496943

In [189]:
import numpy as np

In [205]:
class MyMGDRegressor:
    def __init__(self,learning_rate=0.01,epochs=10):
        self.coef = 0
        self.b = 0
        self.lr = learning_rate
        self.epochs = epochs
    def fit(self,x_train,y_train):
        self.coef = np.ones(x_train.shape[1])
        
        
        for i in range(self.epochs):
            
            y_hat = np.dot(x_train,self.coef) + self.b

            slope_of_b = -2 * np.mean(y_train - y_hat)
            
            slope_of_coef = (-2 * np.dot((y_train - y_hat), x_train))/x_train.shape[0]
            
            
            self.b = self.b - (self.lr*slope_of_b)
            self.coef = self.coef - (self.lr*slope_of_coef)
        print(self.coef)
        print(self.b)
            
    def predict(self,x_test):
        pred = np.dot(x_test,self.coef) + self.b
        return pred

In [261]:
myclass = MyMGDRegressor(0.5,1000)

In [262]:
myclass.fit(x_train,y_train)

[   8.46561346 -166.53547768  499.37280408  316.45100685  -79.9381579
 -122.92084916 -224.01836439  141.62406559  376.68892431  126.77297288]
153.06039950024802


In [263]:
prediction = myclass.predict(x_test)
prediction

array([104.48632658, 176.96702129, 110.00028862, 127.81319264,
       181.58805449,  91.31203622, 135.99001677, 224.23702194,
       154.18179466, 164.07410851, 165.14061045, 181.91541386,
       145.40729095, 236.26561897,  42.0320625 , 146.50323429,
       116.06452187, 199.14395633, 182.73171596, 138.47934174,
       147.8886283 ,  97.16088687, 171.47008602, 172.63414686,
       161.15451641, 180.74095732, 192.38329281, 199.41346301,
       128.95845084, 168.09375069, 263.43437687, 126.97996648,
       194.64360265, 127.53609113, 160.36594901,  64.48967247,
       153.92543173,  94.64569125, 126.46697409, 165.84997807,
       142.53265252, 214.24750518, 130.33874676, 130.01084253,
       152.20108828,  96.84247659, 122.46167978, 254.27636161,
       141.34710349, 191.35610557, 134.66466648, 110.26359815,
       136.05951661, 190.69927848, 163.32727855, 139.43863444,
       121.13337064, 258.38096352, 243.01521946, 152.81715666,
       146.82749619, 132.60061272,  82.36372707, 139.44

In [264]:
r2_score(y_test,prediction)

0.41227009078761867

In [258]:
myclass.b

153.03841232164402

In [259]:
model.coef_

array([  -1.13744712, -212.8867836 ,  540.45536994,  345.20621542,
       -938.23814645,  516.62060367,  172.85885498,  267.87535242,
        732.63230159,   70.07849485])

In [260]:
model.intercept_

153.13441535285003

In [245]:
x_train.shape[1]

10