In [36]:
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression
import numpy as np
import random

In [37]:
x,y = load_diabetes(return_X_y=True)
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [38]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [39]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [40]:
x_test.shape

(89, 10)

In [41]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [42]:
y_pred = model.predict(x_test)
y_pred

array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16

In [43]:
from sklearn.metrics import r2_score

In [44]:
r2_score(y_test,y_pred)

0.4399338661568968

In [158]:
class MySGD:
    def __init__(self,learning_rate,epochs):
        self.coef = None
        self.intercept = None
        self.lr = learning_rate
        self.epochs = epochs
    def fit(self,x_train,y_train):
        # initializing intercept and coefficients
        self.intercept = 0
        self.coef = np.ones(x_train.shape[1])
#         print(self.coef)
        
        for i in range(self.epochs):
            for j in range(x_train.shape[0]):
                index = np.random.randint(0,x_train.shape[0])
                y_hat = np.dot(x_train[index],self.coef) + self.intercept

                # in stochastic gradient descent we do not take mean of y - yhat because we are using rows one by one
                slope_of_intercept = -2*(y_train[index] - y_hat)
                slope_of_coef = (-2*np.dot((y_train[index] - y_hat),x_train[index]))

                self.intercept = self.intercept - (self.lr*slope_of_intercept)
                self.coef = self.coef - (self.lr*slope_of_coef)
        print(self.coef)
        print(self.intercept)
    
    def predict(self,x_test):
        pred = np.dot(x_test,self.coef) + self.intercept
        return pred

In [159]:
myclass = MySGD(0.01,100)

In [160]:
myclass.fit(x_train,y_train)

[  25.65916539 -135.68651876  450.21720928  311.69269579  -21.61554006
  -94.0598138  -189.23693471  116.2979267   415.0104574   117.29213694]
155.91442274814943


In [161]:
prediction = myclass.predict(x_test)
prediction

array([156.44242242, 201.26584314, 135.27062851, 109.26979957,
       265.25500405, 252.9901211 , 114.76128613, 118.73469871,
        97.85103153, 191.39540509, 154.35748543, 177.27461309,
       185.50157531, 143.70359934, 285.795048  ,  91.19051553,
       200.93343352, 150.44563579, 139.06505951, 136.24715195,
       146.35941759, 181.56753064, 160.00159963, 180.03827445,
       130.73798801, 226.42233374, 204.02219975, 110.23611177,
        58.29059991, 244.81196425, 246.42119349, 118.10715541,
        72.07936346, 103.42259047, 208.65856256, 168.1138698 ,
       167.445913  , 198.10114069, 116.73061   , 243.11468253,
       143.70728984, 126.26436329, 191.23049443, 191.90020486,
       177.64127763, 147.94652634, 175.09854355, 299.90899797,
       112.93411755, 179.72588837, 255.95633009, 141.54216424,
       152.87707715, 135.4164579 , 195.86915656, 103.6668625 ,
       141.48861774,  82.03467562, 162.73841414, 155.49958104,
       167.84306189, 167.94752043, 107.43963369, 225.43

In [162]:
r2_score(y_test,prediction)

0.4490879871967023

In [106]:
model.intercept_

151.88331005254167

In [35]:
model.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [163]:
from sklearn.linear_model import SGDRegressor

In [164]:
sgd = SGDRegressor(learning_rate='constant',eta0=0.01)

In [165]:
sgd.fit(x_train,y_train)

SGDRegressor(learning_rate='constant')

In [166]:
sgd.intercept_

array([154.42810561])

In [167]:
sgd.coef_

array([  46.73270532,  -95.35468266,  391.64988833,  271.207724  ,
          1.43515663,  -54.2200907 , -182.29310411,  123.70397982,
        354.48691901,  124.25158501])

In [168]:
prediction_by_sgd = sgd.predict(x_test)
prediction_by_sgd

array([155.67752016, 195.48543055, 139.10332633, 109.80443221,
       253.19758447, 244.28439195, 111.10545937, 117.27176486,
        95.94767783, 188.40918341, 158.52977938, 175.50213747,
       185.75813858, 149.13293449, 267.13117242,  92.5946667 ,
       192.45852164, 144.4229793 , 140.32555351, 139.19279625,
       139.45320252, 187.19483937, 164.74626783, 179.46031986,
       129.14155551, 223.33352762, 199.38127306, 117.49068046,
        62.75169909, 242.68298749, 240.99298604, 119.79497898,
        74.81124935, 108.56183543, 203.69645427, 168.06202927,
       168.10326576, 197.64454306, 116.94104775, 237.45827515,
       140.01324438, 127.81801592, 188.23882122, 188.93081937,
       174.61180392, 147.73415649, 175.19518158, 286.97887534,
       116.93808474, 186.18456869, 244.2533152 , 136.09935338,
       148.3371464 , 145.79344465, 192.82220946, 111.09164493,
       150.97311639,  85.55018563, 160.95693625, 149.3702638 ,
       166.25040319, 171.1041547 , 110.71634751, 213.75

In [169]:
r2_score(y_test,prediction_by_sgd)

0.4440821593925993